### ISSUE TITLE
About consembleEX

### ISSUE THREAD

**Issue by Johnsonzcode** [bioinfo-emlab-unl/consemble#1]
Dear @richardmwaba 
Thank you for your work in consemble!
I found out consembleEX from the latest progress of your [thesis](https://digitalcommons.unl.edu/cgi/viewcontent.cgi?article=1255&context=computerscidiss). It seems a new effective tools!
Can you share the software here?

Best
Johnson

**Comment by richardmwaba** [comment]
Thanks for reaching out, @Johnsonzcode.

We will make ConSemblEX public soon. Just doing housekeeping 😄.

**Comment by Johnsonzcode** [comment]
Thank you so much!
